### PR TITLE
resources: Create efficient javascript arrays resource

### PR DESCRIPTION
**Pull request by supergrecko**
I wrote a tiny article with examples of how Array.filter, .reduce and .map can be used (#87)

### CODE REVIEW

**Comment by veksen** [comment]
This should be merged with https://github.com/the-programmers-hangout/website/blob/master/src/content/resources/javascript/iterative-vs-functional.md

Additionally, I started some extra writeup for that same article, maybe merge our work together?

**Comment by supergrecko** [comment]
Sure, I wasn't sure whether that article was for function vs iterative concepts or the functions themselves. I'll merge the articles together later.

**Comment by veksen** [comment]
My WIP is here: https://github.com/the-programmers-hangout/website/blob/7499b1e21ca315a57bc7ced8d0270d3e80755cf1/src/content/resources/javascript/iterative-vs-functional.md

(https://github.com/the-programmers-hangout/website/commit/7499b1e21ca315a57bc7ced8d0270d3e80755cf1)

**Comment by supergrecko** [comment]
I added a bit more to some of the existing points and fixed the order of the examples and added what they'd evaluate to.

**Comment by veksen** [comment]
I'll be merging this today and we can iterate over it :) sorry for the delay!

**Pull request merged**
