### PR TITLE
feat: Implement Mdx

### PR DESCRIPTION
**Pull request by dfireBird**
I ported mostly every thing to support Mdx plugin.

There is unresolved issues: When I try to add plugin (`gatsby-remark-auto-headers-improved`) to Mdx plugin it throws a load of errors. It's most probably an upstream bug I need more information to open an issues on the repo.

Edit: Installing the plugin with npm and using it Mdx plugins works.

### CODE REVIEW

**Comment by veksen** [comment]
Thank you so much! The failing build is my fault, the master branch build is currently failing, so I need to resolve that first!

**Comment by dfireBird** [comment]
I generated graphQL types just by providing a sample `.graphql` (since there are no graphql files) is that the correct way?

**Comment by dfireBird** [comment]
There is discussion going on in this [issue](https://github.com/gatsbyjs/gatsby/issues/21592) about `module not found` when using local plugins.

**Comment by veksen** [comment]
I did not give up on this :D sorry! I'm waiting and hoping for the issue with the local plugin, sadly `gatsby-remark-auto-headers-improved` is super key... I might need to create a npm package if it's not resolved

**Comment by dfireBird** [comment]
Thanks for explaining it! I thought you put this out for some other reason lol.

**Comment by veksen** [comment]
I've externalized the library to npm https://github.com/the-programmers-hangout/website/pull/311

It's still possible that it doesn't play ball well due to the way the library interacts with Remark, I have to look at that, if so

**Comment by dfireBird** [comment]
I need to add the `gatsby-remark-auto-headers-improved` in both `plugins` option and `gatsbyRemarkPlugins` option because of this [issue](https://github.com/gatsbyjs/gatsby/issues/15486)

**Comment by veksen** [comment]
I'm going to test it today and see if we can finally merge it. Does everything seem stable from your side?

Thank you again for handling this!

**Comment by dfireBird** [comment]
Everything seemed stable on my side.

**Pull request merged**
