### PR TITLE
Add content from #faq and #beginners to the resources section

### PR DESCRIPTION
**Pull request by mhmood-sf**
I hope I didn't mess up the formatting

### CODE REVIEW

**Review by dfireBird — CHANGES_REQUESTED** [review]
Add frontmatter to both markdown like this
image

**Comment by quantomistro** [comment]
@dfireBird Sure. Who should I put as the author? I copy pasted the content from the channels, so I'm not sure who the original author is.

**Comment by quantomistro** [comment]
I left the authors field blank

**Comment by veksen** [comment]
I'm going to test this, otherwise looks good, thanks!

**Pull request closed without merging**
