### PR TITLE
fixed #412, fixed #TODO in side menu animation, fixed <a> text being on top of the header

### LINKED ISSUE #412: Text overflows past viewport and background changes
Here is what I see when I scroll towards the right on an article.

I am trying to find the stylesheet to edit this document and I am unsure what to edit for this. This may be due to an unfamiliarity with Gatsby. But I would think there is a stylesheet to override Gatsby or other libraries.

At any rate, I think one of these container elements may be responsible for this issue.

I am attempting to contribute to open-source projects for the first time, if any of my approach needs more clarification please let me know so I can improve my approach in the future.

### PR DESCRIPTION
**Pull request by Specy**
There are still some issues regarding the header, i dont really like how it is on mobile, it takes up a lot of vertical space and doesn't provide much info, i think it should be removed and instead adding the page path info in the topmost part of the page.

I changed the sidemenu top bar (where there is the logo and tph logo) to have the same size as the header.
Fixes issue #412 
Changed the way the side menu appears, from using left/right to use transform

### CODE REVIEW

**Review by Xetera — COMMENTED** [review]
image

This is still an issue with codeblocks but looks good otherwise

**Comment by Specy** [comment]
Ok i found the reason why, `pre` tags which include code that don't have a language class, have no attributes to define their styling, i saw that all the elements which have a language class have `overflow-x: auto` so i added that to all pre tags, i also included  `min-height:28px` because without it, one line command blocks had a weird Y overflow.

**Comment by Xetera** [comment]
image

`h2` tags also need a word break

**Comment by Specy** [comment]
done

**Review by Xetera — APPROVED** [review]

**Pull request merged**
