### PR TITLE
Better reflect Figma design sheet

### PR DESCRIPTION
**Pull request by haydennyyy**
So far, I've updated the branding, and I've made the breadcrumbs black to match the ones on the Figma.

Issues so far:
- [ ] SVG banner doesn't *quite* fill the space, there's like a 2px margin that I can't seem to fix on either side.
- [ ] Header hasn't been re-styled so everything is inline yet

### CODE REVIEW

**Comment by haydennyyy** [comment]
I believe this also helps a little bit with #27

**Comment by Xetera** [comment]
These are good changes, but I think @aerori wanted to move in a different direction for the design. I'll keep this PR open for now and move any new changes on top of this when we have a more solid idea on how we want to do the homepage design. I'm guessing the figma page will be changing with the new designs sometime soon.

**Comment by haydennyyy** [comment]
@Xetera What, like taking the banner and making it fullscreen? Because if so I'd love to help make that happen

**Comment by veksen** [comment]
Alright so, what I'll be doing is is taking most of the commits, cherry-picking into individual Pull Requests and I'll fix some of the stuff. There are a few problematic things, mainly from the fact that me/Moss/Xetera really knew what was up with the Figma sketches because we're in close communication, but we're shifting the layout a bit towards something else.

Also, in terms of PR, it's nice that there are fixes for types, or some gitignore stuff, but that should totally be included in separate PRs, as they are separate concerns, and unrelated to implementing the design.

**Comment by veksen** [comment]
For the `any` types, we'll be using the generated graphql types! I was just being lazy and pushing it back.

**Comment by veksen** [comment]
I've cherry-picked/merged a few of your changes, including ongoing #63.

Is it possible for you to create new small PRs with the rest of the stuff?

You can exclude everything related to:
- The home page (currently we're not ready to implement it and I have something in progress, we can pair program together if you'd like)
- Your lint fixes related to this own PR
- Type fixes on graphql queries (we will use the generated types)

(I'm not sure if anything remains...)

Thank youuu!

**Comment by haydennyyy** [comment]
@veksen Sure. Lemme just figure out how to cherry-pick lmao

**Pull request closed without merging**
